#pragma once

enum {
	TEXT_PASS_UNIFORM_MVP,
	TEXT_PASS_UNIFORM_GLYPH_SAMPLER,
	TEXT_PASS_UNIFORM_ATLAS_SAMPLER,
	TEXT_PASS_UNIFORM_ATLAS_OFFSET,
	TEXT_PASS_UNIFORM_COLOR,
	TEXT_PASS_UNIFORM_OPACITY,
	TEXT_PASS_UNIFORM_COUNT
};